services:
  postgres:
    image: postgres:17
    container_name: DOCKER-POSTGRES
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manibatauga
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - development-network

  redis:
    image: redis
    container_name: DOCKER-REDIS
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - development-network

volumes:
  postgres_data:
    external: true
    name: docker-postgres_and_redis_postgres_data
  redis_data:
    external: true
    name: docker-postgres_and_redis_redis_data

networks:
  development-network:
   external: true
